FROM ubuntu:20.04
LABEL maintainer="bodsch <bodo@boone-schulz.de>"

ENV DEBIAN_FRONTEND=noninteractive

RUN \
    apt-get update && \
    apt-get install -y \
      git \
      ansible \
      apt-transport-https \
      ca-certificates-java \
      curl \
      init \
      openssh-server \
      openssh-client \
      unzip \
      rsync \
      sudo && \
    apt purge \
      fuse \
      snapd \
      snap-confine \
      squashfuse && \
    apt -y autoremove && \
    rm -rf /var/lib/apt/lists/* && \
# Configure udev for docker integration
    dpkg-divert --local --rename --add /sbin/udevadm && \
    ln -s /bin/true /sbin/udevadm && \
    echo "[local]\nlocalhost ansible_connection=local" > /etc/ansible/hosts

ENTRYPOINT ["/sbin/init"]
