FROM ubuntu:22.04
LABEL maintainer="bodsch <bodo@boone-schulz.de>"

ENV DEBIAN_FRONTEND=noninteractive

COPY rootfs/ /

RUN \
  apt-get update  --assume-yes && \
  apt-get upgrade --assume-yes && \
  apt-get install --assume-yes --no-install-recommends \
    python3-apt \
    python3-setuptools \
    python3-pip \
    git \
    ansible \
    apt-transport-https \
    ca-certificates \
    curl \
    init \
    openssh-server \
    openssh-client \
    unzip \
    rsync \
    sudo && \
  systemctl set-default multi-user.target && \
  systemctl disable getty@tty1.service && \
  ln --symbolic \
    /usr/bin/python3 /usr/bin/python && \
  mkdir /etc/ansible && \
  echo -e "[local]\nlocalhost ansible_connection=local" > /etc/ansible/hosts && \
  systemctl set-default multi-user.target && \
  systemctl disable getty@tty1.service && \
  apt purge \
    fuse \
    snapd \
    snap-confine \
    squashfuse && \
  apt autoremove \
    --assume-yes && \
  apt-get clean && \
  rm --recursive --force \
    /tmp/* \
    /var/lib/apt/lists/* \
    /var/cache/debconf/* \
    /usr/share/doc/* \
    /root/.cache \
    /root/.config 2> /dev/null && \
  /usr/bin/info.sh

ENTRYPOINT ["/sbin/init"]
