#!/usr/bin/env bash

set -x

docker buildx build \
  --platform ${PLATFORM} \
  --file=${DISTRIBUTION}-ansible/Dockerfile.${DISTRIBUTION}-${DISTRIBUTION_VERSION} \
  --tag=${DOCKER_NAME_SPACE}/ansible-${DISTRIBUTION}:${DISTRIBUTION_VERSION} \
  ${DISTRIBUTION}-ansible

