#!/usr/bin/env bash

set -x

pushd ${DISTRIBUTION}-ansible

docker build \
  --file=Dockerfile.${DISTRIBUTION}-${DISTRIBUTION_VERSION} \
  --tag=${DOCKER_NAME_SPACE}/ansible-${DISTRIBUTION}:${DISTRIBUTION_VERSION} \
  .

popd
