FROM alpine:latest
LABEL maintainer="bodsch <bodo@boone-schulz.de>"

# Install Ansible
RUN \
  apk add --no-cache \
    git \
    ansible \
    sudo \
    openssh \
    unzip \
    tar \
    rsync \
    libc6-compat \
    fuse-dev

VOLUME ["/sys/fs/cgroup"]

ENTRYPOINT ["/sbin/init"]
