name: Build

on:
  schedule:
    - cron: '0 18 * * sun'
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug
  push:
    branches:
      - 'master'
      - 'feature/**'
      - '!doc/**'
    paths:
      - "!Makefile"
      - "!README.md"
      - "*-ansible/**"
  pull_request:
    branches:
      - 'master'
      - 'feature/**'
      - '!doc/**'
    paths:
      - "!Makefile"
      - "!README.md"
      - "*-ansible/**"

jobs:
  build:
    name: ${{ matrix.distribution.image }}-${{ matrix.distribution.version }}
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        distribution:
          - image: almalinux
            version: "8"
            platform: "linux/amd64,linux/arm64/v8"
          - image: almalinux
            version: "9"
            platform: "linux/amd64,linux/arm64/v8"

          - image: alpine
            version: "latest"
            platform: "linux/amd64,linux/arm64/v8"

          - image: amazonlinux
            version: "2"
            platform: "linux/amd64,linux/arm64/v8"

          - image: archlinux
            version: "latest"
            platform: "linux/amd64"

          - image: artixlinux
            version: "latest"
            platform: "linux/amd64"

          - image: debian
            version: "10"
            platform: "linux/386,linux/amd64,linux/arm64/v8"
          - image: debian
            version: "11"
            platform: "linux/amd64,linux/arm64/v8"
          - image: debian
            version: "testing"
            platform: "linux/amd64"

          - image: gentoo
            version: "latest"
            platform: "linux/amd64"
          - image: gentoo-systemd
            version: "latest"
            platform: "linux/amd64"

          - image: oraclelinux
            version: "8"
            platform: "linux/amd64,linux/arm64/v8"
          - image: oraclelinux
            version: "9"
            platform: "linux/amd64,linux/arm64/v8"

          - image: rockylinux
            version: "8"
            platform: "linux/amd64"
          - image: rockylinux
            version: "9"
            platform: "linux/amd64"

          - image: ubuntu
            version: "22.04"
            platform: "linux/amd64,linux/arm64/v8"
          - image: ubuntu
            version: "22.10"
            platform: "linux/amd64,linux/arm64/v8"
          - image: ubuntu
            version: "23.04"
            platform: "linux/amd64,linux/arm64/v8"


    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Inspec
        run: curl https://omnitruck.chef.io/install.sh | sudo bash -s -- -P inspec -v 4.24.8

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker images
        run: |
          docker build \
            --no-cache \
             \
            --file=${{ matrix.distribution.image }}-ansible/Dockerfile.${{ matrix.distribution.image }}-${{ matrix.distribution.version }} \
            --tag=bodsch/ansible-${{ matrix.distribution.image }}:${{ matrix.distribution.version }} \
            ${{ matrix.distribution.image }}-ansible

      - name: Test Docker images
        run: |
          container_id=$(mktemp)
          sudo docker run \
            --detach \
            --privileged \
            -v /sys/fs/cgroup:/sys/fs/cgroup:ro \
            bodsch/ansible-${{ matrix.distribution.image }}:${{ matrix.distribution.version }} > "${container_id}"

          inspec exec tests/inspec --chef-license accept-silent -t docker://$(cat ${container_id})

      - name: Build Docker images on all platforms
        run: |
          docker buildx build \
            --platform ${{ matrix.distribution.platform }} \
            --file=${{ matrix.distribution.image }}-ansible/Dockerfile.${{ matrix.distribution.image }}-${{ matrix.distribution.version }} \
            --tag=bodsch/ansible-${{ matrix.distribution.image }}:${{ matrix.distribution.version }} \
            ${{ matrix.distribution.image }}-ansible
